baseURL = 'https://afalta.me'
languageCode = 'en-us'
title = 'faltawy 😄'
theme = 'typo'

[taxonomies]
tag = 'portfolio'
category = "blog"
googleAnalytics = "G-0QX292BDBQ"

[params]
description = "Ahmad Falta's personal portfolio and blog"

theme = 'auto'
colorPalette = 'default'
hideHeader = false
footerContent=" "

homeCollectionTitle = '------------'
homeCollection = 'blogs'
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ahmad-falta/"

[[params.social]]
name = "github"
url = "https://github.com/faltawy"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blogs"
url = "/blogs"

[[params.menu]]
name = "snippets"
url = "/snippets"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

[params.giscus]
enable = true
repo = "faltawy/falta-website"
repoid = "R_kgDOKMEL0A"
category = "General"
categoryid = "DIC_kwDOKMEL0M4CjS2Q"
mapping = "pathname"
theme = "dark"
reactions = "1"
metadata = "0"
emitMetadata = "0"
